const head = `[Script Info]
; Script generated by Aegisub 9706-cibuilds-20caaabc0
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:24000/1001:40000:1920:1080:47:163:254:
Video AR Value: 1.777778
Video Zoom Percent: 0.750000
Active Line: 1
Video Position: 1183

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: 日文-Liella,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H009C46A5,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-外-Liella,Tsukushi A Round Gothic,45,&H00FFFFFF,&H000000FF,&H009C46A5,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,8,0,0,0,1
Style: 中文-Liella,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H009C46A5,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-外-Liella,FZFW ZhuZi A YuanS,39,&H00FFFFFF,&H000000FF,&H009C46A5,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,8,0,0,10,1
Style: 日文-f-Liella,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H009C46A5,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Kanon,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00277FFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Kanon,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00277FFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Kanon,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00277FFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Keke,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00D9D143,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Keke,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00D9D143,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Keke,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00D9D143,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Chisato,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00906EFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Chisato,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00906EFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Chisato,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00906EFF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Sumire,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00409C4B,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Sumire,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00409C4B,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Sumire,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00409C4B,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Ren,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00A00000,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Ren,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00A00000,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Ren,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00A00000,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Kinako,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H0031B1C1,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Kinako,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H0031B1C1,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Kinako,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H0031B1C1,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Mei,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H003535FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Mei,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H003535FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Mei,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H003535FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Shiki,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00A6B07F,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Shiki,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00A6B07F,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Shiki,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00A6B07F,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Natsumi,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00C451FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Natsumi,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00C451FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Natsumi,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00C451FF,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Margarete,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00F095D8,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Margarete,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00F095D8,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Margarete,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00F095D8,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-Tomari,Tsukushi A Round Gothic,54,&H00FFFFFF,&H000000FF,&H00AEA727,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 中文-Tomari,FZFW ZhuZi A YuanS,64,&H00FFFFFF,&H000000FF,&H00AEA727,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1
Style: 日文-f-Tomari,Tsukushi A Round Gothic,30,&H00FFFFFF,&H000000FF,&H00AEA727,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

const lyrics = ``;
const arr = lyrics.split('\n').slice(4);
let result = head;
for (let i = 0; i < arr.length; i += 2) {
    const zh = arr[i];
    const ja = arr[i + 1];
    result += `\nDialogue: 0,0:00:00.00,0:00:00.00,中文-,,0,0,0,,{\\fad(200,200)\\pos(960,1020)}${zh}\nDialogue: 0,0:00:00.00,0:00:00.00,日文-,,0,0,0,,{\\fad(200,200)\\pos(960,1075)}${ja}`;
}
result;
