/**
 * @file 将 ./input/ 中，开头4行为注释的txt日中字幕稿转换为使用Dialogue的简易.ass字幕。使用node.js执行。
 * @author Kiyoshi(kiyoshi.kusunoki@gmail.com)
 */

/**
 * 毫秒数转ass时间格式
 * 
 * @param {number} seconds100 毫秒数
 * @returns {string} 类似 0:00:00.00 的ass适用时间格式
 */
function secondsToTime(seconds100) {
    const hours = Math.floor(seconds100 / 360000);
    const minutes = Math.floor((seconds100 - hours * 360000) / 6000);
    const seconds = Math.floor(
        (seconds100 - hours * 360000 - minutes * 6000) / 100
    );
    const miS = Math.floor(
        seconds100 - hours * 360000 - minutes * 6000 - seconds * 100
    );

    return `${hours}:${("" + minutes).padStart(2, "0")}:${(
        "" + seconds
    ).padStart(2, "0")}.${("" + miS).padStart(2, "0")}`;
}

function to(text, eachTime) {
    const arr = text.split("\n").slice(4);
let result = `[Script Info]
; Script generated by Aegisub 9706-cibuilds-20caaabc0
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:24000/1001:40000:1920:1080:47:163:254:
Video AR Value: 1.777778
Video Zoom Percent: 0.750000
Active Line: 1
Video Position: 1183

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: 日文-furigana,Tsukushi B Round Gothic,35,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,1,2,35,35,20,1
Style: 中文-furigana,Noto Serif SC,35,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,1,2,35,35,20,1
Style: Default-furigana,Arial,10,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 中文,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H009C46A5,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H009C46A5,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 日文-Ren,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00A00000,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Ren,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00A00000,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Kanon,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00277FFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Kanon,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00277FFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Keke,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00D9D143,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Keke,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00D9D143,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Chisato,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00906EFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Chisato,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00906EFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Sumire,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00409C4B,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Sumire,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00409C4B,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Kinako,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H0029A2AB,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Kinako,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H0029A2AB,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Mei,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H003535FF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Mei,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H003535FF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Shiki,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H009BB07F,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Shiki,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H009BB07F,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Natsumi,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00C451FF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Natsumi,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00C451FF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Margarete,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00F095D8,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Margarete,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00F095D8,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1
Style: 日文-Tomari,Tsukushi A Round Gothic,65,&H00FFFFFF,&H000000FF,&H00E2D24C,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,2,8,35,35,20,1
Style: 中文-Tomari,FZFW ZhuZi A YuanS,54,&H00FFFFFF,&H000000FF,&H00E2D24C,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,2,2,35,35,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`
    for (let i = 0; i < arr.length; i += 2) {
        const zh = arr[i];
        const ja = arr[i + 1];
        let add = 0;
        // if (i / 2 > 0) {
        //     add = (i / 2) * 30;
        // }
        const inTime = secondsToTime((i / 2) * eachTime + add);
        const outTime = secondsToTime((i / 2 + 1) * eachTime + add);
        result += `Dialogue: 0,${inTime},${outTime},日文,,0,0,0,,{\\fad(200,200)}${ja}\nDialogue: 0,${inTime},${outTime},中文,,0,0,0,,{\\fad(200,200)}${zh}\n`;
    }
    return result;
}

const fs = require("fs");

const inputPath = "./input";
const outputPath = "./output";

// 读取 input 文件夹下的所有文件
const files = fs.readdirSync(inputPath);

// 遍历所有文件
files.forEach((file) => {
    // 获取文件名
    const fileName = file.replace(/\.[^.]+$/, "");

    // 创建 output 文件夹下的文件
    const outputFile = fs.createWriteStream(`${outputPath}/${fileName}.ass`);

    // 读取文件内容
    const data = fs.readFileSync(`${inputPath}/${file}`);
    const data1 = to(data.toString(), 40);

    // 写入文件内容
    outputFile.write(data1);

    // 关闭文件流
    outputFile.end();
});
